Repository helm/acceptance-testing, pull requests merged in 2019-10, with the labels that each got.

#48 Robot params are strings not bools
  lib/Sh.py
Labels: size/XS

#50 Make helm unavailable on path
  scripts/completion-tests/completionTests.sh
Labels: size/S

#49 Simplify python libs by using generic Sh lib
  lib/Helm.py
  lib/Kubectl.py
  testsuites/kubernetes_versions.robot
Labels: size/M

#51 Tests for dynamic completion of --output flag
  scripts/completion-tests/completionTests.sh
Labels: size/S

#52 Some modifications to helm get
  scripts/completion-tests/completionTests.sh
Labels: size/XS

#54 Remove 'all' subcommand for get until accepted
  scripts/completion-tests/completionTests.sh
Labels: size/XS

#53 Add initial github actions
  .github/workflows/acceptance-tests-pr.yml
  .github/workflows/acceptance-tests.yml
  .gitignore
  Makefile
  README.md
  lib/Kind.py
  scripts/acceptance.sh
  scripts/completion-tests/test-completion.sh
  scripts/github-actions-ci.sh
  testsuites/kubernetes_versions.robot
  testsuites/repos.robot
Labels: size/L

#55 helm get now accepts the all subcommand
  scripts/completion-tests/completionTests.sh
Labels: size/XS

#56 Add completion tests for completing charts
  scripts/completion-tests/completionTests.sh
Labels: size/M

#57 helm plugin 'remove' is now 'uninstall'
  scripts/completion-tests/completionTests.sh
Labels: size/XS
