Repository helm/acceptance-testing, pull requests merged in 2020-06, with the labels that each got.

#84 Change dir-mount to copy-in for the completion tests' images.
  scripts/completion-tests/test-completion.sh
Labels: size/S

#81 Add checks in Shells test suite
  scripts/completion-tests/test-completion.sh
Labels: size/L

#85 Add tests for completion of --version flag
  scripts/completion-tests/completionTests.sh
Labels: size/M
